### ISSUE TITLE
Missing the doc about balance changes

### ISSUE THREAD

**Issue by telezhnaya** [near/wiki#43] opened 2022-03-28 11:01 UTC
There was a doc about balance changes, located at `wiki/ecosystem/near-token/token-balance.md`, answering the question `Why does my balance change?`

Where can I find it now?

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:07
Hey, that was removed due to its complexity. It didn't suit the target audience of the NEAR Wiki. It still exists in other forked repos, though:

https://github.com/ocularmagic/wiki/blob/master/ecosystem/near-token/token-balance.md

**Comment by telezhnaya** [comment] 2022-03-28 11:10
So, it's not possible to find it anywhere, right? We have wiki, docs and nomicon. Are you sure we have no place for this doc?

**Comment by telezhnaya** [comment] 2022-03-28 11:12
I find it's extremely odd that we just remove the doc only because it was too complex in someone's opinion, especially when we have no alternative for it.

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:17
The doc hasn't disappeared forever, it can, and maybe should be folded into Docs or Nomicon. You can find a link to it above. 

There is no use in having three separate repositories for highly technical information IMO. The Wiki should serve as the 'go-to' place for end users and those interested. To that extent, it almost serves as a switchboard to direct developers, validators, etc to the appropriate resources (docs/nomicon/etc).

Perhaps we need to align on what the goals of the Wiki are:

1. Be able to convey or direct new NEAR users to introductory resources necessary across 3 different levels of theoretical and technical familiarity with blockchain and cryptocurrency: completely unfamiliar, moderately familiar, familiar but new to NEAR.

2. Be host to a number of 'how-to' guides and act as a launching point for individuals who want to learn more about specific sectors.
For example, we should have an overview of the Guilds system and the ability to direct those who land on it to create or join a Guild

3. Empower community moderators to answer the most commonly asked questions about NEAR (and about using NEAR) by directing users to the NEAR Wiki

--

**Comment by telezhnaya** [comment] 2022-03-28 11:24
I insist that it's not appropriate to just delete the document. 
If you feel that wiki isn't the right place, you should find the right place and move it there. You can't just delete it. 

I am the author of this doc and I spent 15 minutes realizing that it was just dropped (it's really insane). I needed to go to the local git history on my machine and copy the file from there, because the users asked me about the doc.
For the users, it's not possible to find it at any chance.

Please find all the files you deleted, restore them, and put them into the projects that you find more appropriate.

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:25
Ok, please refrain from publishing technical documentation in wiki.near.org for the time being

**Comment by telezhnaya** [comment] 2022-03-28 11:27
This issue should be closed only when all deleted docs will appear here or in the other projects

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:29
They will not be restored to wiki.near.org for at least ~ 1 week since there's a content audit ongoing, if ever (since they should live elsewhere). Will ping when PR is in Nomicon

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:32
https://github.com/near/NEPs/pull/344

**Comment by telezhnaya** [comment] 2022-03-28 11:32
what about other docs that were deleted?

**Comment by DavidIsNEAR** [comment] 2022-03-28 11:35
Going through the history now

**Comment by telezhnaya** [comment] 2022-03-28 13:56
@bucanero it's still not accessible at docs.near.org

**Comment by bucanero** [comment] 2022-03-28 14:12
> @bucanero it's still not accessible at docs.near.org

Could you try this URL, https://docs.near.org/docs/concepts/token-balance ? It's working on my end. 🤔

**Comment by telezhnaya** [comment] 2022-03-28 14:15
Works fine now! Thank you @bucanero 
Please close the issue when we are sure we haven't missed anything

**Comment by bucanero** [comment] 2022-03-28 14:25
> The below, as well as some others, will likely be removed after the audit but will merge it into Nomicon:
> 
> https://wiki.near.org/technology/docs/access-keys

I've created a PR for the "Access keys" article: https://github.com/near/docs/pull/1038

@DavidIsNEAR  let me know if you're removing it so I can merge the PR.

**Comment by DavidIsNEAR** [comment] 2022-03-28 14:27
Thanks @bucanero, will be removed some time next week after the audit is complete. Will keep this issue open until then 🎉

**Comment by thisisjoshford** [comment] 2022-03-30 21:25
Hey @DavidIsNEAR and @telezhnaya! Rebecca just flagged this to me and just wanted to chime in. 

@DavidIsNEAR we are aligned with wiki having information that is designed for more high-level non-technical users, but there will be a shared glossary / terminology that people will need to know. Access keys and token balances certainly can have levels of complexity when explaining them and agree that wiki should be high level and then link out to docs or nomicon  to give users the option to dive deeper. Let's work closely across teams/orgs to shape how that looks moving forward. 

Also, please ping @bucanero or me before we remove any content to avoid any loss of information, broken links, and internal/external confusion. I will be sure to attend the next wiki meeting to make sure we are all on the same page.

**Comment by DavidIsNEAR** [comment] 2022-05-05 08:29
Hey guys,

Have relayed changes to @thisisjoshford via Slack - will close this for now

**Comment by telezhnaya** [comment] 2023-01-18 07:41
Again, I can't find my article anywhere 🤦 
https://docs.near.org/docs/concepts/token-balance gives 404
I searched through nomicon, wiki, docs: no luck
Is it deleted again?

**Comment by telezhnaya** [comment] 2023-01-18 07:52
Knowing it could happen again, I just store raw MD file on my laptop with that doc. I feel sad I was right

I put it here because now it's the only possibility for me to refer to it
[token-balance.md](https://github.com/near/wiki/files/10443452/token-balance.md)

**Comment by bucanero** [comment] 2023-01-31 19:56
> Again, I can't find my article anywhere 🤦 https://docs.near.org/docs/concepts/token-balance gives 404 I searched through nomicon, wiki, docs: no luck Is it deleted again?

hi @telezhnaya , I'll check on our docs repository and ping back about your "Token balance" article.

**Comment by telezhnaya** [comment] 2023-02-02 09:43
I don't see the page still
https://wiki.near.org/search?q=balance

**Comment by humanman** [comment] 2023-02-02 11:04
@telezhnaya can you confirm this is the page? https://wiki.near.org/overview/tokenomics/balance

I’m not sure why it’s not indexed in the search. I’ll make a new issue for that.

**Comment by humanman** [comment] 2023-02-02 11:32
Closing since This issue is a duplicate of #71

**Closed by humanman** 2023-02-02 11:32 UTC
